#Subroutine names

subroutine Knockback 0
subroutine applyCustomHp 1
subroutine clearCustomHp 2
subroutine resetFrenemies 3
subroutine resetStats 4
subroutine resetStatuses 5
subroutine executeUppercut 6
subroutine enableAllAbilities 7
subroutine disableAllAbilities 8
subroutine changelogText 9
subroutine resetHero 10
subroutine removeTankPassive 11
subroutine storeOverhealth 12
subroutine botAim2Target 13


