#!mainFile "../../main.opy"
#Subroutine names

subroutine Knockback
subroutine applyCustomHp
subroutine clearCustomHp
subroutine resetFrenemies
subroutine resetStats
subroutine resetStatuses
subroutine executeUppercut
subroutine enableAllAbilities
subroutine disableAllAbilities
subroutine changelogText
subroutine resetHero
subroutine removeTankPassive
subroutine botAim2Target
subroutine applySignedMoveSpeed
subroutine clearMoveSpeedDebuffs
